import { Product } from "./app/shared/models/product";

export const sample_products: Product[] = [
    {
        id: '1',
        name: 'pshycho-bunny T-shirt',
        description: 'Camiseta roja de algodón',
        price: 199.99,
        stock: 20,
        images: ['assets/images/item-images/T-shirts/bunny_t-shirt.jpg'],
        category: 'playeras',
        size: ['chica', 'mediana', 'grande'],
        color: 'rojo',
      },
      {
        id: '2',
        name: 'true messiah T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/item-images/T-shirts/jesus_t-shirt.jpg'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '3',
        name: 'D puppet master T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '4',
        name: 'satanic-panic T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '5',
        name: 'zombie-disco T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '6',
        name: 'cia-be glowing T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '7',
        name: 'T H1v3 T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '8',
        name: 'Machine god T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '9',
        name: 'good times T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '10',
        name: 'franken-bitch T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '11',
        name: 'thunder bird T-shirt',
        description: 'Camiseta roja de algodón',
        price: 199.99,
        stock: 20,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana', 'grande'],
        color: 'rojo',
      },
      {
        id: '12',
        name: ' acid spit T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '13',
        name: ' nonagon T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '14',
        name: 'clown T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '15',
        name: 'paranoid vigilante T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '16',
        name: 'hangover T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '17',
        name: 'rawwr T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '18',
        name: 'glitch T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '19',
        name: 'ones-and-zeros T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
      {
        id: '20',
        name: 'Dahmer T-shirt',
        description: 'Camiseta azul de algodón',
        price: 189.99,
        stock: 10,
        images: ['assets/images/not_found.png'],
        category: 'playeras',
        size: ['chica', 'mediana'],
        color: 'azul',
      },
]